// authentication based actions
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const PREV_LOGIN = "PREV_LOGIN";
export const LOGIN_FAILURE_CLR_MSG = "LOGIN_FAILURE_CLR_MSG";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";



// products based actions
export const PRODUCT_LISTING_START = "PRODUCT_LISTING_START";
export const PRODUCT_LISTING_SUCCESS = "PRODUCT_LISTING_SUCCESS";
export const PRODUCT_LISTING_FAILURE = "PRODUCT_LISTING_FAILURE";
export const PRODUCT_LISTING_EMPTY = "PRODUCT_LISTING_EMPTY";

// cart actions
export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAILURE = "CART_FAILURE";
export const CART_DEFAULT = "CART_DEFAULT";

export const CART_ADD_START = "CART_ADD_START";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAILURE = "CART_ADD_FAILURE";
export const CART_ADD_CLEAR_MESSAGE = "CART_ADD_CLEAR_MESSAGE";

export const CART_REMOVE_START = "CART_REMOVE_START";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_REMOVE_FAILURE = "CART_REMOVE_FAILURE";
export const CART_REMOVE_CLEAR_MESSAGE = "CART_REMOVE_CLEAR_MESSAGE";

// orders based actions
export const ORDER_LISTING_START = "ORDER_LISTING_START";
export const ORDER_LISTING_SUCCESS = "ORDER_LISTING_SUCCESS";
export const ORDER_LISTING_FAILURE = "ORDER_LISTING_FAILURE";
export const ORDER_LISTING_EMPTY = "ORDER_LISTING_EMPTY";
export const ORDER_SET_FILTER = "ORDER_SET_FILTER";